### ISSUE TITLE
add some configs

### ISSUE THREAD

**Issue by gjmhmm8** [TagnumElite/ProjectE-Integration#108]
1 When an item can be crafted by multiple recipes, and the recipes have different emc values, you can choose the highest, lowest, average or no emc
2 Whether to set an item to have no emc when there is a recipe that can exploit emc
3 You can configure emc for everything (including energy, fluids, gases, etc.), and it will automatically generate related emc

**Comment by TagnumElite** [comment]
1. I don't want to touch ProjectE EMC generation and calculation because that could break down the line.
2. Already Possible: `/projecte setemc 0` with said item in hand
3. While this is possible and I am supporting fluids and gases, but due to their nature of being in the thousands, (A bucket being 1000ml) it is a bit iffy.

**Comment by gjmhmm8** [comment]
lquid and gases can set emc with Bucket，not mb，and mapping with 
fraction
